default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library_dev
  pool: 5
  role: lib_pr
  password: password

test:
  <<: *default
  database: db_library_test
  pool: 5
  role: lib_pr
  password: password

production:
  <<: *default
  database: db_library_production
  username: orpwzlux
  password: q5yLinhon0xScT7iZE_U_D7FqLQUaupY
  host: postgres://orpwzlux:q5yLinhon0xScT7iZE_U_D7FqLQUaupY@castor.db.elephantsql.com/orpwzlux
